# Generated by Django 2.2 on 2020-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200313_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='surnname',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='demo.Book'),
        ),
    ]
